// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list_news.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_news_default = defineTool({
  name: "list_news",
  title: "\u5217\u51FA\u65B0\u95FB",
  description: "\u83B7\u53D6\u7EA2\u6E56\u6587\u5B66\u793E\u5DF2\u53D1\u5E03\u7684\u65B0\u95FB\u5217\u8868\uFF0C\u6309\u53D1\u5E03\u65E5\u671F\u5012\u5E8F\u3002",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("\u8FD4\u56DE\u6761\u6570\uFF0C\u9ED8\u8BA4 10")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("news").select("id, title, category, published_at, cover_url").eq("is_published", true).order("published_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_news.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_news_default = defineTool2({
  name: "get_news",
  title: "\u83B7\u53D6\u65B0\u95FB\u8BE6\u60C5",
  description: "\u6839\u636E ID \u83B7\u53D6\u4E00\u6761\u65B0\u95FB\u7684\u5B8C\u6574\u6B63\u6587\u4E0E\u5143\u6570\u636E\u3002",
  inputSchema: { id: z2.string().uuid().describe("\u65B0\u95FB ID (UUID)") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("news").select("*").eq("id", id).eq("is_published", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "\u672A\u627E\u5230\u8BE5\u65B0\u95FB" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { news: data } };
  }
});

// src/lib/mcp/tools/list_events.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_events_default = defineTool3({
  name: "list_events",
  title: "\u5217\u51FA\u6D3B\u52A8",
  description: "\u83B7\u53D6\u6587\u5B66\u793E\u6D3B\u52A8\u5217\u8868\u3002\u53EF\u9009\u6309 upcoming / past \u8FC7\u6EE4\u3002",
  inputSchema: {
    filter: z3.enum(["upcoming", "past", "all"]).optional().describe("\u65F6\u95F4\u8FC7\u6EE4\uFF0C\u9ED8\u8BA4 all"),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ filter, limit }) => {
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("events").select("id, title, description, event_date, location, category").eq("is_active", true);
    const now = (/* @__PURE__ */ new Date()).toISOString();
    if (filter === "upcoming") q = q.gte("event_date", now).order("event_date", { ascending: true });
    else if (filter === "past") q = q.lt("event_date", now).order("event_date", { ascending: false });
    else q = q.order("event_date", { ascending: false });
    const { data, error } = await q.limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_members.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_members_default = defineTool4({
  name: "list_members",
  title: "\u5217\u51FA\u5386\u5C4A\u6210\u5458",
  description: "\u67E5\u8BE2\u6587\u5B66\u793E\u5386\u5C4A\u6210\u5458\u6863\u6848\uFF0C\u53EF\u6309\u5C4A\u522B\u6216\u59D3\u540D\u5173\u952E\u5B57\u8FC7\u6EE4\u3002",
  inputSchema: {
    term: z4.string().optional().describe("\u5C4A\u522B\uFF0C\u4F8B\u5982 2024\u7EA7"),
    search: z4.string().optional().describe("\u59D3\u540D\u5173\u952E\u5B57"),
    limit: z4.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ term, search, limit }) => {
    const supabase = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("members").select("id, name, term, role_title, bio, featured_quote, major, city, literary_tags");
    if (term) q = q.eq("term", term);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q.limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_works.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_works_default = defineTool5({
  name: "list_works",
  title: "\u5217\u51FA\u4F5C\u54C1",
  description: "\u67E5\u8BE2\u5DF2\u5BA1\u6838\u901A\u8FC7\u3001\u516C\u5F00\u53D1\u8868\u7684\u6587\u5B66\u4F5C\u54C1\uFF08\u8BD7\u6B4C\u3001\u5C0F\u8BF4\u3001\u6563\u6587\u7B49\uFF09\u3002",
  inputSchema: {
    genre: z5.string().optional().describe("\u4F53\u88C1\uFF0C\u4F8B\u5982 \u8BD7\u6B4C / \u5C0F\u8BF4 / \u6563\u6587"),
    search: z5.string().optional().describe("\u6807\u9898\u6216\u6B63\u6587\u5173\u952E\u5B57"),
    limit: z5.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ genre, search, limit }) => {
    const supabase = createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("submissions").select("id, title, content, author_name, genre, created_at").eq("status", "approved").order("created_at", { ascending: false });
    if (genre) q = q.eq("genre", genre);
    if (search) q = q.or(`title.ilike.%${search}%,content.ilike.%${search}%`);
    const { data, error } = await q.limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_my_profile.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_my_profile_default = defineTool6({
  name: "get_my_profile",
  title: "\u83B7\u53D6\u6211\u7684\u4E2A\u4EBA\u8D44\u6599",
  description: "\u83B7\u53D6\u5F53\u524D\u767B\u5F55\u7528\u6237\u5728\u7EA2\u6E56\u6587\u5B66\u793E\u7684\u4E2A\u4EBA\u8D44\u6599\u3001\u89D2\u8272\u4EE5\u53CA\u5173\u8054\u7684\u6210\u5458\u6863\u6848\u3002",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\u672A\u767B\u5F55" }], isError: true };
    }
    const supabase = createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const uid = ctx.getUserId();
    const [profile, roles, member] = await Promise.all([
      supabase.from("profiles").select("*").eq("user_id", uid).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", uid),
      supabase.from("members").select("*").eq("user_id", uid).maybeSingle()
    ]);
    const result = {
      email: ctx.getUserEmail(),
      user_id: uid,
      profile: profile.data,
      roles: (roles.data ?? []).map((r) => r.role),
      member: member.data
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list_my_submissions.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_my_submissions_default = defineTool7({
  name: "list_my_submissions",
  title: "\u6211\u7684\u6295\u7A3F",
  description: "\u5217\u51FA\u5F53\u524D\u767B\u5F55\u7528\u6237\u63D0\u4EA4\u8FC7\u7684\u6240\u6709\u4F5C\u54C1\u53CA\u5BA1\u6838\u72B6\u6001\u3002",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\u672A\u767B\u5F55" }], isError: true };
    }
    const supabase = createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("submissions").select("id, title, genre, status, created_at, reviewer_notes").eq("author_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create_submission.ts
import { createClient as createClient8 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";
var create_submission_default = defineTool8({
  name: "create_submission",
  title: "\u63D0\u4EA4\u4F5C\u54C1",
  description: "\u4EE5\u5F53\u524D\u767B\u5F55\u7528\u6237\u8EAB\u4EFD\u5411\u7EA2\u6E56\u6587\u5B66\u793E\u63D0\u4EA4\u4E00\u7BC7\u4F5C\u54C1\uFF08\u5F85\u7BA1\u7406\u5458\u5BA1\u6838\uFF09\u3002",
  inputSchema: {
    title: z6.string().min(1).max(200).describe("\u4F5C\u54C1\u6807\u9898"),
    content: z6.string().min(1).describe("\u4F5C\u54C1\u6B63\u6587"),
    genre: z6.string().min(1).describe("\u4F53\u88C1\uFF1A\u8BD7\u6B4C / \u5C0F\u8BF4 / \u6563\u6587 \u7B49"),
    author_name: z6.string().min(1).describe("\u4F5C\u8005\u7F72\u540D")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, content, genre, author_name }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\u672A\u767B\u5F55\uFF0C\u65E0\u6CD5\u6295\u7A3F" }], isError: true };
    }
    const supabase = createClient8(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("submissions").insert({
      author_id: ctx.getUserId(),
      title,
      content,
      genre,
      author_name,
      status: "pending"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `\u6295\u7A3F\u6210\u529F\uFF0C\u7B49\u5F85\u5BA1\u6838\u3002\u4F5C\u54C1 ID: ${data.id}` }],
      structuredContent: { submission: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wuroxjmdjwvncvoqztza";
var mcp_default = defineMcp({
  name: "honghu-literary-society-mcp",
  title: "\u7EA2\u6E56\u6587\u5B66\u793E MCP",
  version: "0.1.0",
  instructions: "\u7EA2\u6E56\u6587\u5B66\u793E\u5B98\u7F51\u7684\u5DE5\u5177\u96C6\u3002\u53EF\u67E5\u8BE2\u65B0\u95FB\u3001\u6D3B\u52A8\u3001\u5386\u5C4A\u6210\u5458\u3001\u516C\u5F00\u4F5C\u54C1\uFF1B\u767B\u5F55\u7528\u6237\u53EF\u67E5\u770B\u4E2A\u4EBA\u8D44\u6599\u3001\u6295\u7A3F\u8BB0\u5F55\u5E76\u63D0\u4EA4\u65B0\u4F5C\u54C1\u3002",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_news_default,
    get_news_default,
    list_events_default,
    list_members_default,
    list_works_default,
    get_my_profile_default,
    list_my_submissions_default,
    create_submission_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
